# Generated by Django 5.1.4 on 2024-12-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('surname', models.CharField(max_length=100, verbose_name='фамилия')),
                ('second_name', models.CharField(max_length=100, verbose_name='отчество')),
                ('email', models.EmailField(max_length=100, verbose_name='электронная почта')),
                ('comment', models.TextField(max_length=400, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='тема письма')),
                ('message', models.TextField(max_length=1500, verbose_name='тело письма')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_send_date', models.DateTimeField(verbose_name='дата и время первой рассылки')),
                ('periodicity', models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], default='daily', max_length=15)),
                ('status', models.CharField(choices=[('draft', 'создана'), ('sent', 'отправлена'), ('completed', 'завершена')], default='draft', max_length=15)),
                ('clients', models.ManyToManyField(to='mail_sending.client')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail_sending.message')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_date', models.DateTimeField()),
                ('attempt_status', models.CharField(choices=[('success', 'успешно'), ('failure', 'не успешно')], default='failure', max_length=10)),
                ('response', models.TextField(blank=True, null=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_sending.mailing')),
            ],
        ),
    ]
